- id: swagger-validation
  name: swagger-validation
  entry: swagger-cli
  description: Hook to validate swagger specs.
  language: docker
  files: (openapi|swagger).*\.(json|ya?ml)$
  args: ["validate"]

